### ISSUE TITLE
feat type is not working properly

### ISSUE THREAD

**Issue by mashal1996** [hoopher/commit-linter#1]
I was tring to commit the code as following 

git commit -am "feat: some changes"

but I got the following error

Traceback (most recent call last):
  File ".git/hooks/commit-msg", line 49, in <module>
    main()
  File ".git/hooks/commit-msg", line 46, in main
    newCommit.write(commitPrefix + ": " + commitEmojie + commitPostfix)
TypeError: cannot concatenate 'str' and 'NoneType' objects

and I changed it to refactor and it worked.

**Comment by Sulaiman-SM** [comment]
Issue has been resolved , thanks @mashal1996

**Comment by hoopher** [comment]
Issue has been solved, thanks @mashal1996
