### ISSUE TITLE
Using a colon (":") in the commit message.

### ISSUE THREAD

**Issue by loskost** [hoopher/commit-linter#3]
Hi!

When using a colon in a commit message twice, a part of the message is lost.
Apparently, the error is in this place:

https://github.com/hoopher/commit-linter/blob/a294798acc2247a09295cf35b7442aeb645b7f2e/commit_linter/hooks/commit-msg#L38

Example of a message:
```
fix: bla-bla

A very important commit

ref: https://task.domain.com
```
After executing the hook:
```
fix: bla-bla

A very important commit

ref
```
Suggestion: specify the number of splits in `.split()`:
```python
commitPostfix = ss.split(':', 1)[1] 
```

**Comment by hoopher** [comment]
Hi @loskost 

Thank you for the suggestion, I have fixed the code in the last commit

I will push the changes ASAP to the pypi

Appreciate your contribution
